services:
  app:
    image: drakona/php:8.2-symfony
    depends_on:
      - db
    volumes:
      - .:/srv
    working_dir: /srv
    command: php -S 0.0.0.0:8000 -t public
    ports:
      - "8000:8000"

  nginx:
    image: drakona/nginx:8-symfony
    depends_on:
      - app
    ports:
      - "8000:80"
    volumes:
      - .:/srv
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mariadb:10
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: api
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db-data: {}
